### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by jyn514**
Fixes CI for https://github.com/rust-lang/rustwide/pull/53.

### CODE REVIEW

**Review by emilyalbini — APPROVED** [review]

**Comment by jyn514** [comment]
> error: this function's return value is unnecessarily wrapped by `Option`

This is a bug in clippy, changing the return type would be a breaking change. It's fixed on nightly but not stable.

**Comment by jyn514** [comment]
Oh wait, that's for a `pub(crate)` function. I'll fix it.

**Comment by jyn514** [comment]
> Oh wait, that's for a `pub(crate)` function. I'll fix it.

Nope, it's intentionally meant to be the same return type as `windows::current_user`.

**Comment by jyn514** [comment]
Failure looks unrelated to my change :/
```
[INFO  rustwide::cmd] running `Command { std: "docker" "start" "-a" "aa0794c5521d231481ac2c06a84ed33417ee7733cd94c06317744a107202ac1b", kill_on_drop: false }`
[INFO  rustwide::cmd] [stderr]    Compiling out-of-memory v0.1.0 (/opt/rustwide/workdir)
[INFO  rustwide::cmd] [stderr] error: linker `cc` not found
[INFO  rustwide::cmd] [stderr]   |
[INFO  rustwide::cmd] [stderr]   = note: No such file or directory (os error 2)
[INFO  rustwide::cmd] [stderr] 
[INFO  rustwide::cmd] [stderr] error: aborting due to previous error
[INFO  rustwide::cmd] [stderr] 
[INFO  rustwide::cmd] [stderr] error: could not compile `out-of-memory`
```

**Comment by emilyalbini** [comment]
Removing https://github.com/rust-lang/rustwide/blob/76a2475ee73152d390479fbfb09dc46253372293/tests/utils/mod.rs#L25-L28 should do the trick.

**Comment by jyn514** [comment]
I can't replicate the clippy failures locally. I think CI might be using an old version?

**Comment by emilyalbini** [comment]
@jyn514 hmm, seems like there are some new warnings introduced by 1.51 :sweat_smile: 

I think we can `#![allow]` the capitalization one, I'm not going to break backward compatibility due to it.

**Review by emilyalbini — APPROVED** [review]

**Pull request merged**
