### PR TITLE
Allow to pass registry ssh key

### PR DESCRIPTION
**Pull request by l4l**

### CODE REVIEW

**Comment by emilyalbini** [comment]
Hello, and thanks for the PR!

The code changes look good, but I'm worried about the extensibility of the API, as [git2 supports more authentication methods](https://docs.rs/git2/0.13.21/git2/struct.Cred.html) than just in-memory SSH keys. I think the most extensible solution would be to make the `AlternativeRegistry` struct public, with an API similar to this:

```rust
use rustwide::{AlternativeRegistry, Crate};

let mut registry = AlternativeRegistry::new("https://github.com/rust-lang/crates.io-index");
registry.authenticate_with_ssh_key("key");

let krate = Crate::registry(&registry, "name", "version");
```

**Comment by l4l** [comment]
Oh, it seems I missed a notification for that thread, sorry for that.

`AlternativeRegistry` as a pub item makes a perfect sense, although it seems to be a breaking change. Is it fine? 

**UPD:** it seems current changes are breaking anyway due to new `Crate::registry` arg. So I just proceed with the proposed option.

**Comment by emilyalbini** [comment]
Sounds good! We're also pre-1.0 on rustwide, so it's fine to make breaking changes, especially to make the API easier to extend in the future!

**Comment by jyn514** [comment]
@pietroalbini I think this is waiting on your review.

**Comment by gregvirgin** [comment]
I'm currently working with cloudsmith.io, which will only support git credentials. We're configuring our own image to get around this, but want to see if this method could support adding to .git-credentials on the image as well.

**Review by emilyalbini — APPROVED** [review]

**Comment by emilyalbini** [comment]
Sorry for the late merge, will release this soon!

**Comment by emilyalbini** [comment]
Released rustwide 0.15.0 with this change.

**Pull request merged**
