### PR TITLE
Allow removing a component

### LINKED ISSUE #19: Allow removing a component
If a component is not available on the latest nightly, rustup will refuse to update. The workaround is to first remove the component from the toolchain, but `rustwide` doesn't expose this in the `Toolchain` API.

See also https://github.com/rust-lang/docs.rs/issues/357#issuecomment-606252725

### PR DESCRIPTION
**Pull request by kellda**
This implement the possibility of removing a component from a toolchain.
Fixes #19.

### CODE REVIEW

**Comment by emilyalbini** [comment]
This needs to be rebased over the latest master, otherwise it looks good!

**Comment by kellda** [comment]
Done.

**Comment by emilyalbini** [comment]
Thanks!

**Comment by emilyalbini** [comment]
Released rustwide 0.9.0 with this change!

**Comment by kellda** [comment]
Great !

**Pull request merged**
