### PR TITLE
Use image name with hash after pulling

### PR DESCRIPTION
**Pull request by Nemo157**

### CODE REVIEW

**Comment by emilyalbini** [comment]
Is there a reason for this change?

**Comment by Nemo157** [comment]
Mostly that this will log the exact image used, so that it is possible to pull it down later and inspect it from the build logs on docs.rs (assuming that hub.docker.com don't garbage collect unreferenced images, which I haven't seen them do yet).

(Just the log line added is not enough, that's not part of the logs that make it onto docs.rs, which is why it replaces the image name as well for when used as part of future commands).

**Comment by emilyalbini** [comment]
Ok, that's great!

Could you add a line to the changelog?

**Comment by emilyalbini** [comment]
Thanks!

**Pull request merged**
