### PR TITLE
Update asyncronous dependencies

### PR DESCRIPTION
**Pull request by Kixiron**
* Updated `tokio`, `reqwest`, `base64` and `tiny_http`
* Removed `tokio-process` (Deprecated in favor of the `process` feature of `tokio`)
* Replaced `futures` with `futures-util` and updated (Less dependencies, the extra features of `futures` weren't being used)

### CODE REVIEW

**Comment by jyn514** [comment]
If you update base64 to 0.11 it will remove another duplicate dependency:
```
$ cargo tree -d
base64 v0.10.1
└── rustwide v0.6.1 (/home/joshua/src/rustwide)

base64 v0.11.0
└── reqwest v0.10.4
    └── rustwide v0.6.1 (/home/joshua/src/rustwide)
...
```

**Comment by jyn514** [comment]
`tiny_http` also causes a lot of duplicates, you could try updating it to 0.7. It's only a dev-dependency though.

**Comment by jyn514** [comment]
Updating to base64 0.12 actually introduced a duplicate, up to you whether you think it's worth fixing or not.

```
cargo tree -d
base64 v0.11.0
└── reqwest v0.10.4
    └── rustwide v0.6.1 (/home/joshua/src/rustwide)

base64 v0.12.1
└── rustwide v0.6.1 (/home/joshua/src/rustwide)
```

**Review by jyn514 — APPROVED** [review]

**Review by emilyalbini — APPROVED** [review]

**Comment by emilyalbini** [comment]
Thanks!

**Pull request merged**
